from sqlalchemy import MetaData, Table, Column, Integer, String, Float, Boolean

metadata_obj = MetaData()

users_table = Table(
    'users',
    metadata_obj,
    Column('telegram_chat_id', Integer, primary_key=True),
    Column('blofin_api_key', String),
    Column('blofin_api_secret', String),
    Column('blofin_api_password', String),
    Column('exchange_id', String, default='blofin'),
    Column('starting_equity', Float),
    Column('is_active', Boolean),
    Column('total_wins', Integer, default=0),
    Column('total_losses', Integer, default=0),
    Column('total_trades_opened', Integer, default=0),
    Column('cumulative_pnl', Float, default=0.0),
    Column('last_fetch_timestamp', Integer, default=0),
    Column('strategy', String, default='Valkyrie Elite Scalper'),
    Column('active_crypto_strategy', String, default='Valkyrie Elite Scalper'),
    Column('active_stock_strategy', String, default='None'),
    Column('risk_pct', Float, default=1.0),
    Column('stock_risk_pct', Float, default=2.0),
    Column('enabled_symbols', String),
    Column('referred_by', Integer),
    Column('premium_expiry', Integer, default=0),
    Column('referral_count', Integer, default=0),
    Column('has_open_positions', Boolean, default=False),
    Column('undercover_mode', Boolean, default=False),
    Column('source_wallet', String),
    Column('last_audit_stats', String),
    Column('referral_credits', Float, default=0.0),
    Column('full_name', String),
    Column('username', String),
    Column('is_admin', Boolean, default=False),
    Column('custom_equity_type', String, default='all'),
    Column('custom_equity_value', Float),
    Column('alpaca_api_key', String),
    Column('alpaca_api_secret', String),
    Column('alpaca_endpoint', String),
    Column('alpaca_start_equity', Float),
    Column('premium_referrals', Integer, default=0),
    Column('premium_expired_notified', Boolean, default=False),
    Column('had_premium_before', Boolean, default=False),
    Column('referral_reward_triggered', Boolean, default=False),
    Column('bingx_futures_type', String, default='standard'),
    Column('coinbase_sandbox', Integer, default=1),
)

webusers_table = Table(
    'webusers',
    metadata_obj,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('email', String, unique=True, nullable=False),
    Column('password_hash', String),
    Column('google_id', String, unique=True),
    Column('full_name', String),
    Column('avatar_url', String),
    Column('telegram_chat_id', Integer),
    Column('exchange_id', String, default='blofin'),
    Column('api_key', String),
    Column('api_secret', String),
    Column('api_password', String),
    Column('alpaca_api_key', String),
    Column('alpaca_api_secret', String),
    Column('alpaca_endpoint', String),
    Column('is_active', Boolean, default=False),
    Column('risk_pct', Float, default=1.0),
    Column('stock_risk_pct', Float, default=2.0),
    Column('enabled_symbols', String),
    Column('hide_dollars', Boolean, default=False),
    Column('custom_equity_type', String, default='all'),
    Column('custom_equity_value', Float),
    Column('active_crypto_strategy', String, default='Valkyrie Elite Scalper'),
    Column('active_stock_strategy', String, default='None'),
    Column('source_wallet', String),
    Column('premium_expiry', Integer, default=0),
    Column('referral_credits', Float, default=0.0),
    Column('referred_by', Integer),
    Column('referral_count', Integer, default=0),
    Column('total_wins', Integer, default=0),
    Column('total_losses', Integer, default=0),
    Column('cumulative_pnl', Float, default=0.0),
    Column('has_open_positions', Boolean, default=False),
    Column('history_cache', String),
    Column('last_audit_stats', String),
    Column('created_at', Integer),
    Column('reset_token', String),
    Column('reset_token_expiry', Integer),
    Column('email_notifications', Integer, default=1),
    Column('email_frequency', String, default='realtime'),
    Column('browser_notifications', Integer, default=1),
    Column('public_key', String),
    Column('encrypted_private_key', String),
    Column('bingx_futures_type', String, default='standard'),
    Column('alpaca_start_equity', Float),
    Column('coinbase_sandbox', Integer, default=1),
    Column('developer_api_key', String, unique=True),
)

theoretical_trades_table = Table(
    'theoreticaltrades',
    metadata_obj,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('symbol', String),
    Column('strategy', String),
    Column('side', String),
    Column('entry_price', Float),
    Column('tp_price', Float),
    Column('sl_price', Float),
    Column('open_time', Integer),
    Column('close_time', Integer),
    Column('status', String, default='open'),
    Column('position_size', Float, default=0.0),
    Column('pnl_raw', Float, default=0.0),
    Column('pnl_pct', Float, default=0.0),
    Column('pnl_usdt', Float, default=0.0),
)

alpaca_active_trades_table = Table(
    'alpacaactivetrades',
    metadata_obj,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('telegram_chat_id', Integer),
    Column('symbol', String),
    Column('qty', Float),
    Column('entry_price', Float),
    Column('tp_price', Float),
    Column('sl_price', Float),
    Column('open_time', Integer),
    Column('close_time', Integer),
    Column('close_price', Float),
    Column('pnl_raw', Float),
    Column('pnl_pct', Float),
    Column('status', String, default='open'),
    Column('web_user_id', Integer),
)

portfolio_balance_history_table = Table(
    'portfoliobalancehistory',
    metadata_obj,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('user_id', Integer, nullable=False),
    Column('timestamp', Integer, nullable=False),
    Column('encrypted_crypto_balance', String),
    Column('encrypted_stock_balance', String),
)

config_table = Table(
    'config',
    metadata_obj,
    Column('key', String, primary_key=True),
    Column('value', String),
)

gift_codes_table = Table(
    'giftcodes',
    metadata_obj,
    Column('code', String, primary_key=True),
    Column('target_chat_id', Integer),
    Column('target_username', String),
    Column('expiry_days', Integer, default=30),
    Column('is_used', Boolean, default=False),
    Column('created_at', Integer),
)

portfolio_positions_table = Table(
    'portfoliopositions',
    metadata_obj,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('user_id', Integer, nullable=False),
    Column('symbol', String, nullable=False),
    Column('name', String),
    Column('category', String, nullable=False),
    Column('quantity', Float, nullable=False),
    Column('avg_entry_price', Float, nullable=False),
    Column('purchase_date', String, nullable=False),
    Column('dividend_yield', Float, default=0.0),
    Column('created_at', Integer, nullable=False),
)

portfolio_analysis_history_table = Table(
    'portfolioanalysishistory',
    metadata_obj,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('user_id', Integer, nullable=False),
    Column('score', Integer, nullable=False),
    Column('analysis_text', String, nullable=False),
    Column('action_plan', String, nullable=False),
    Column('timestamp', Integer, nullable=False),
)

