/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./*.{html,js}"],
  darkMode: "class",
  theme: {
      extend: {
          "colors": {
              "surface-container-high": "#262a37",
              "tertiary-fixed-dim": "#00e479",
              "on-tertiary-container": "#005d2d",
              "primary-container": "#00d4ff",
              "error-container": "#93000a",
              "surface-container-lowest": "#0a0e1a",
              "on-error-container": "#ffdad6",
              "outline-variant": "#3c494e",
              "tertiary-container": "#00df76",
              "on-surface-variant": "#bbc9cf",
              "on-surface": "#dfe2f3",
              "surface-container-low": "#171b28",
              "tertiary-fixed": "#60ff99",
              "outline": "#859398",
              "on-primary-fixed-variant": "#004e5f",
              "on-primary-fixed": "#001f27",
              "surface-tint": "#3cd7ff",
              "on-background": "#dfe2f3",
              "surface-variant": "#313442",
              "on-tertiary": "#003919",
              "on-error": "#690005",
              "surface-container-highest": "#313442",
              "surface-container": "#1b1f2c",
              "tertiary": "#00ff88",
              "primary-fixed": "#b4ebff",
              "on-tertiary-fixed": "#00210c",
              "secondary-container": "#ffdb3c",
              "inverse-on-surface": "#2c303d",
              "on-primary": "#003642",
              "secondary": "#fff9ef",
              "error": "#ffb4ab",
              "inverse-primary": "#00677e",
              "on-secondary": "#3a3000",
              "surface-bright": "#353946",
              "primary-fixed-dim": "#3cd7ff",
              "surface-dim": "#0f131f",
              "surface": "#0f131f",
              "background": "#0f131f",
              "on-secondary-fixed-variant": "#544600",
              "primary": "#a8e8ff",
              "secondary-fixed-dim": "#e9c400",
              "on-secondary-container": "#725f00",
              "secondary-fixed": "#ffe16d",
              "on-primary-container": "#00586b",
              "on-tertiary-fixed-variant": "#005228",
              "inverse-surface": "#dfe2f3",
              "on-secondary-fixed": "#221b00"
          },
          "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
          },
          "spacing": {
              "section-gap": "24px",
              "stack-gap": "12px",
              "inline-gap": "8px",
              "card-padding": "16px",
              "container-margin": "16px"
          },
          "fontFamily": {
              "label-md": ["Inter"],
              "numeric-data": ["Inter"],
              "label-sm": ["Inter"],
              "headline-sm": ["Inter"],
              "body-lg": ["Inter"],
              "body-md": ["Inter"],
              "headline-md": ["Inter"],
              "display-lg": ["Inter"]
          },
          "fontSize": {
              "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500"}],
              "numeric-data": ["18px", {"lineHeight": "24px", "fontWeight": "700"}],
              "label-sm": ["10px", {"lineHeight": "12px", "letterSpacing": "0.08em", "fontWeight": "600"}],
              "headline-sm": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
              "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
              "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
              "headline-md": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
              "display-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700"}]
          }
      },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
